server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
            search-locations: file://${user.home}/Desktop/etc/git-local-repo
        git:
          uri: https://github.com/wo-okis/spring-cloud-config
          default-label: main
          username: wo-okis
          password: ${PRIVATE_GITHUB_TOKEN} # GitHub Personal Access Token
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
          - beans
          - info
          - busrefresh
